### ISSUE TITLE
Use dotenv package

### ISSUE THREAD

**Issue by XhmikosR** [emedvedev/slackin-extended#52]
Should make things simpler

https://github.com/motdotla/dotenv

**Comment by emedvedev** [comment]
It's generally a good idea, but not sure if it's worth it in this particular case. For some deployment methods passing env variables is way easier than adding a file (e.g. I'd rather do it through `docker -e` than `docker cp` or rebuilding the container). I'd leave the particulars of storing those variables to the ops folks so that they could do whatever they prefer :)

**Comment by XhmikosR** [comment]
I totally agree, but IIRC dotenv won't overwrite any env vars with the same name so it should work the same I think.

**Comment by emedvedev** [comment]
I'm just afraid that it can create unnecessary confusion, but if we only mention it as an extra option in README and don't force it, then I'd be fine with it. :)

**Comment by XhmikosR** [comment]
I just want an easy way for local development. Now I have to set the vars every time.

Let's leave it open for a while :)
